title: Luong Hoang Minh
logo: "/images/pfp2.jpg?raw=true"
description: >
  <br>
  International Business student at the University of Economics Ho Chi Minh City. This portfolio showcases my work as I transition into the field of data analytics.
  <br><br>
  Email: <span id="email">minhlhoangvn@gmail.com</span>
  <button id="copyBtn" onclick="copyEmail()" style="margin-left: 5px; transition: all 0.3s ease;">Copy</button>
  
  <script>
    function copyEmail() {
      const emailText = document.getElementById("email").innerText;
      const btn = document.getElementById("copyBtn");
      
      navigator.clipboard.writeText(emailText).then(() => {
        const originalText = btn.innerText;
        const originalColor = btn.style.color;
  
        btn.innerText = "âœ”"; 
        btn.style.color = "#28a745";
        btn.style.fontWeight = "bold";
  
        setTimeout(() => {
          btn.innerText = originalText;
          btn.style.color = originalColor;
          btn.style.fontWeight = "normal";
        }, 3000);
      });
    }
  </script>
  <br><br>
  <a href="https://www.linkedin.com/in/lhminh" target="_blank" rel="noopener noreferrer">LinkedIn</a>
  <br><br>
  <a href="https://raw.githubusercontent.com/lhm2904/lhm2904.github.io/3c842d2d90e6455f36839d7b6b60e0b365a76ac2/pdf/LuongHoangMinh_CV.pdf">Download my resume</a>

  
theme: jekyll-theme-minimal
google_analytics: G-XZ6GNVH6NF # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
